client:
  acks: "1"
  retries: 1
  batch.size: 128
  linger.ms: 1
  enable.idempotence: false
  partitioner.class: org.pizazz.kafka.support.RandomPartitioner
config:
  mode: ASYNC
  transactionProcessor:
    classpath: org.pizazz.kafka.producer.TransactionProcessor
  senderProcessor: 