client:
  acks: "1"
  retries: 1
  batch.size: 128
  linger.ms: 1
  enable.idempotence: false
  partitioner.class: org.pizazz2.kafka.core.RandomPartitioner
config:
  mode: ASYNC
  transaction-processor: ""
  sender-processor: ""